blank_issues_enabled: false
contact_links:
  - name: Junte-se a nós no Discord, para qualquer dúvida ou solicitação
    url: https://renildomarcio.com.br/discord.html
    about: Por favor, não abra nenhum problema além de relatar bugs
